### ISSUE TITLE
Change the value of AuthnCacheContext? 

### ISSUE THREAD

**Issue by ghost** [LolHens/docker-httpd#3]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by lhns** [comment]
I don't think this is the right place to do this. The image is just debian with httpd installed. You could provide your own config when running the container if you want.

**Comment by morsik** [comment]
@LolHens : this is some bot… he raised this identical issue to every httpd project that is docker-related...
I reported abuse.

**Comment by lhns** [comment]
Okay thank you! I will just close these issues and hope that he doesn't have some other "vulnerabilities" for us. ^^
